### ISSUE TITLE
Downloading models from bioimage.io fails for several models

### ISSUE THREAD

**Issue by constantinpape** [ilastik/bioimage-io-models#29]
I tried to download some of the new ilastik models from bioimage.io, but ran into several issues:

## Download not possible

For these models, the card opening after clicking the `ilastik` icon does not offer a `Download` button and the `bioimageio-pacakger` says "No model weights available":
![Screenshot from 2021-07-07 18-07-39](https://user-images.githubusercontent.com/4263537/124794712-97601900-df4f-11eb-97ab-b581f36d2cf5.png)
This happens for
- "2D UNet Arabidopsis Ovules"
- "ISBI2012-2d-BoundaryModel"

## Download possible, but files are missing

For these models the download is possible, but some files are missing, e.g.:
![Screenshot from 2021-07-07 18-09-48](https://user-images.githubusercontent.com/4263537/124795156-0dfd1680-df50-11eb-9841-4a3511c5ef71.png)

Models with missing files:
- "3D UNet Lateral Root Primordia Cell Boundaries" (test files and env file missing)
- "3D UNet Lateral Root Primordia Cell Boundaries" (test files and env file missing)

cc @oeway @FynnBe @k-dominik

**Comment by oeway** [comment]
Thanks for the report!

> Download not possible

There is a bug in the update step for saving the source RDF file name, I will fix that.

> Download possible, but files are missing

This should be fixed in the model itself, @k-dominik @FynnBe Could you look into this?

**Comment by oeway** [comment]
Hi @k-dominik I just fixed a bug for the updating feature, while it will work for the two models, it would be better if you can use the update feature to update the two items: "2D UNet Arabidopsis Ovules", "ISBI2012-2d-BoundaryModel". You just need to login and click step by steps, and the information will be corrected on zenodo.

**Comment by constantinpape** [comment]
> I just fixed a bug for the updating feature, while it will work for the two models

Thanks @oeway, this works now.

I don't think we need to update these models, I think we should rather re-upload all the ilastik models with a lab zenodo account at some point soon.

> This should be fixed in the model itself, @k-dominik @FynnBe Could you look into this?

Thanks for checking. I think this is probably not super urgent, we can also check this once re-uploading to the shared zenodo account.

**Comment by constantinpape** [comment]
Looks like there are a couple of other issues with the plantseg models.
For one, the test data is not stored as npy, but npz.

**Comment by constantinpape** [comment]
For all other models the `environment.yaml` seems to be missing.

**Comment by k-dominik** [comment]
Hello @constantinpape,

thx for checking that out. I'd suggest to wait with reuploading until 0.3.2 is considered final. So far I had to change the models manually quite often already because of "implicit" spec changes (model upload adds fields, model download change(d/s) and this is not a viable solution.  (you summarized this in your https://github.com/bioimage-io/spec-bioimage-io/issues/154 neatly).

As far the lab account, I'm happy to share my sandbox.zenodo credentials. Once we go out of the sandbox we should consider using maybe an account associated with Anna's email.

**Comment by constantinpape** [comment]
> I'd suggest to wait with reuploading until 0.3.2 is considered final.

Yes, I agree.



> As far the lab account, I'm happy to share my sandbox.zenodo credentials. Once we go out of the sandbox we should consider using maybe an account associated with Anna's email.

Ok, sounds good!
