### ISSUE TITLE
Use small icons to speed up loading

### ISSUE THREAD

**Issue by oeway** [ilastik/bioimage-io-models#3]
Could you please use a smaller icon in the manifest [here](https://github.com/ilastik/bioimage-io-models/blob/0a52f29f1f9be5589d2c0b1daff5a6fd668a9123/manifest.bioimage.io.yaml#L7-L8)?

For `icon` and `logo`: `100x100` png image would be good.

Also please replace the `icon` in [the BioEngineApp](https://github.com/ilastik/bioimage-io-models/blob/master/src/Ilastik-app.imjoy.html#L17).

**Comment by constantinpape** [comment]
I have added a smaller icon (it's not quite 100x100, because we wanted to keep the aspect ratio, but close to it)
